-- StudyGotchi Database Schema
-- Supabase에서 SQL Editor로 실행하세요.

-- 1. 사용자 프로필
create table if not exists profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text,
  display_name text not null default 'User',
  role text not null default 'student' check (role in ('student', 'teacher')),
  gems int not null default 100,
  items jsonb not null default '{"revive_potion": 0, "cheat_sheet": 0}',
  created_at timestamptz default now()
);

-- Enable RLS
alter table profiles enable row level security;

create policy "Users can read own profile" on profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on profiles
  for update using (auth.uid() = id);

create policy "Users can insert own profile" on profiles
  for insert with check (auth.uid() = id);

-- 2. 펫 테이블
create table if not exists pets (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  level int not null default 1,
  experience int not null default 0,
  intelligence int not null default 0,
  hunger int not null default 100,
  is_dead boolean not null default false,
  last_fed_at timestamptz default now(),
  created_at timestamptz default now(),
  character_sprite text not null default 'rabbit' check (character_sprite = 'rabbit'),
  room_type text not null default 'bedroom' check (room_type in ('bedroom', 'kitchen', 'classroom', 'shop')),
  nutrition jsonb not null default '{"carbs":50,"protein":50,"fat":50,"vitamin":50,"mineral":50}',
  food_inventory jsonb not null default '{}',
  points int not null default 0,
  mbti text default 'ENFP'
);

-- 기존 테이블 마이그레이션 (이미 pets 테이블이 있는 경우 Supabase SQL Editor에서 실행)
-- supabase/migrations/001_add_pet_character_columns.sql 파일 내용을 실행하세요.

alter table pets enable row level security;

create policy "Users can read own pet" on pets
  for select using (auth.uid() = user_id);

create policy "Users can update own pet" on pets
  for update using (auth.uid() = user_id);

create policy "Users can insert own pet" on pets
  for insert with check (auth.uid() = user_id);

create policy "Users can delete own pet" on pets
  for delete using (auth.uid() = user_id);

-- 3. 학습 로그 (Context용)
create table if not exists study_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  content text not null,
  created_at timestamptz default now()
);

alter table study_logs enable row level security;

create policy "Users can read own study_logs" on study_logs
  for select using (auth.uid() = user_id);

create policy "Users can insert own study_logs" on study_logs
  for insert with check (auth.uid() = user_id);

create policy "Users can delete own study_logs" on study_logs
  for delete using (auth.uid() = user_id);

-- 4. 시험 문제 (교사 출제)
create table if not exists exams (
  id bigint generated by default as identity primary key,
  room_id uuid,
  question text not null,
  model_answer text not null,
  is_active boolean default false,
  created_at timestamptz default now()
);

alter table exams enable row level security;

create policy "Anyone can read active exams" on exams
  for select using (is_active = true);

create policy "Teachers can insert exams" on exams
  for insert with check (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'teacher'
    )
  );

create policy "Teachers can update exams" on exams
  for update using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'teacher'
    )
  );

-- 5. 시험 결과 (로그)
create table if not exists exam_results (
  id bigint generated by default as identity primary key,
  exam_id bigint references exams(id),
  user_id uuid references auth.users(id) on delete cascade not null,
  pet_answer text,
  is_correct boolean,
  score int,
  created_at timestamptz default now()
);

alter table exam_results enable row level security;

create policy "Users can read own exam_results" on exam_results
  for select using (auth.uid() = user_id);

create policy "Users can insert own exam_results" on exam_results
  for insert with check (auth.uid() = user_id);

-- 6. 결제 테이블
create table if not exists payments (
  order_id text primary key,
  amount int,
  user_id uuid references auth.users(id),
  status text check (status in ('READY', 'DONE', 'CANCELED')),
  created_at timestamptz default now()
);

alter table payments enable row level security;

create policy "Users can read own payments" on payments
  for select using (auth.uid() = user_id);

create policy "Users can insert own payments" on payments
  for insert with check (auth.uid() = user_id);

create policy "System can update payments" on payments
  for update using (auth.uid() = user_id);

-- 7. 교실 테이블
create table if not exists classrooms (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  teacher_id uuid references auth.users(id) on delete cascade not null,
  code text not null unique,
  created_at timestamptz default now()
);

alter table classrooms enable row level security;

create policy "Anyone can read classrooms" on classrooms
  for select using (true);

create policy "Teachers can insert classrooms" on classrooms
  for insert with check (auth.uid() = teacher_id);

-- 8. 교실 멤버 테이블
create table if not exists classroom_members (
  id uuid default gen_random_uuid() primary key,
  classroom_id uuid references classrooms(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  joined_at timestamptz default now(),
  unique(classroom_id, user_id)
);

alter table classroom_members enable row level security;

create policy "Anyone can read classroom_members" on classroom_members
  for select using (true);

create policy "Students can join classrooms" on classroom_members
  for insert with check (auth.uid() = user_id);
